
export const Routes = {
    // pages
    VM:{path:'/build-projects'},
    fullstack:{path:'/assessment'},
    Presentation: { path: "/" },
    DashboardOverview: { path: "/dashboard/overview" },
    DashboardOverviewAdmin: { path: "/admin/dashboard/overview" },
    Transactions: { path: "/challenges" },
    Settings: { path: "/settings" },
    Upgrade: { path: "/upgrade" },
    QuizStartNow: { path: "/Assessments/full-stack" },
    Billing: { path: "/examples/billing" },
    Invoice: { path: "/examples/invoice" },
    Signin: { path: "/sign-in" },
    Signup: { path: "/sign-up" },
    ForgotPassword: { path: "/examples/forgot-password" },
    ResetPassword: { path: "/examples/reset-password" },
    Lock: { path: "/examples/lock" },
    NotFound: { path: "/examples/404" },
    ServerError: { path: "/examples/500" },

    // docs
    QuizOverview: { path: "/full-stack/overview" },
    BuildProject: { path: "/Projects/workspace" },
    Question: { path: "/Question" },
    QuizQuestion: { path: "/Quiz/" },

    // components
    Accordions: { path: "/components/accordions" },
    Alerts: { path: "/components/alerts" },
    Badges: { path: "/components/badges" },
    Widgets: { path: "/widgets" },
    Breadcrumbs: { path: "/components/breadcrumbs" },
    Buttons: { path: "/components/buttons" },
    Forms: { path: "/components/forms" },
    Modals: { path: "/components/modals" },
    Navs: { path: "/components/navs" },
    Navbars: { path: "/components/navbars" },
    Pagination: { path: "/components/pagination" },
    Popovers: { path: "/components/popovers" },
    Progress: { path: "/components/progress" },
    Tables: { path: "/components/tables" },
    Tabs: { path: "/components/tabs" },
    Tooltips: { path: "/components/tooltips" },
    Toasts: { path: "/components/toasts" },
    WidgetsComponent: { path: "/components/widgets" },
    PageTrafficTable: { path: "/components/quiz" },
    AdminUserDetailedReports: { path: "/admin/user-detailed-reports"},
    UserDetails: { path: "/admin/user/:userid/:username", basePath: "/admin/user"},
    AdminQuizDetailedReports: { path: "/admin/quiz-detailed-reports"},
    QuizDetails: { path: "/admin/quiz/:quizid/:quizname", basePath: "/admin/quiz"}
};